
import React from 'react';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { useUser } from '@/contexts/UserContext';
import { useLeaveManagementContext } from '@/contexts/LeaveManagementContext';
import { Form } from '@/components/ui/form';
import { Button } from '@/components/ui/button';
import { leaveFormSchema, LeaveFormValues } from '@/utils/leaveTypes';
import { useLeaveFormCalculations } from '@/hooks/useLeaveFormCalculations';
import { LeaveDateSelector } from '@/components/leave/LeaveDateSelector';
import { LeaveTypeSelector } from '@/components/leave/LeaveTypeSelector';
import { LeaveFormDetails } from '@/components/leave/LeaveFormDetails';
import { LeaveApprovalWorkflow } from '@/components/leave/LeaveApprovalWorkflow';
import { getApprovers } from '@/services/leaveRequestService';
import { visionProStyles } from '@/utils/visionProStyles';
import { Calendar, FileType, MessageSquare, GitBranch, Send } from 'lucide-react';

interface LeaveRequestFormProps {
  onSubmit?: () => void;
}

export function LeaveRequestForm({ onSubmit }: LeaveRequestFormProps) {
  const { currentUser } = useUser();
  const { createLeaveRequest } = useLeaveManagementContext();
  const approvers = getApprovers();
  
  const form = useForm<LeaveFormValues>({
    resolver: zodResolver(leaveFormSchema),
    defaultValues: {
      reason: "",
    },
  });

  const { calculatedHours, selectedLeaveType } = useLeaveFormCalculations(form.watch);

  async function handleSubmit(data: LeaveFormValues) {
    if (!currentUser) return;

    // Create the leave request
    const leaveRequest = {
      id: '', // Will be generated by database
      user_id: currentUser.id,
      start_date: data.start_date.toISOString().split('T')[0],
      end_date: data.end_date.toISOString().split('T')[0],
      leave_type: data.leave_type as any,
      status: 'pending' as const,
      hours: calculatedHours,
      reason: data.reason,
      approval_level: 1,
      current_approver: approvers[0]?.id,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      approvals: approvers.map((approver, index) => ({
        id: `${Date.now()}-${index}`,
        leave_request_id: '',
        approver_id: approver.id,
        approver_name: approver.name,
        status: 'pending' as const,
        level: approver.level
      }))
    };

    const success = await createLeaveRequest(leaveRequest);
    
    if (success) {
      // If there's an onSubmit handler, call it
      if (onSubmit) {
        onSubmit();
      }
      
      // Reset the form
      form.reset();
    }
  }

  return (
    <div className="space-y-8">
      <div className="text-center mb-8">
        <h2 className={`text-2xl font-bold mb-2 ${visionProStyles.primaryText} text-white drop-shadow-lg`}>
          請假申請
        </h2>
        <p className="text-white/70 font-medium drop-shadow-md">
          請填寫以下資訊提交您的請假申請
        </p>
      </div>

      <Form {...form}>
        <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-8">
          {/* 日期選擇區塊 */}
          <div className="backdrop-blur-xl bg-white/20 rounded-3xl border border-white/30 shadow-xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 bg-blue-500/80 rounded-lg flex items-center justify-center">
                <Calendar className="h-4 w-4 text-white" />
              </div>
              <h3 className="text-lg font-semibold text-white drop-shadow-md">請假日期</h3>
            </div>
            <LeaveDateSelector 
              form={form} 
              calculatedHours={calculatedHours} 
            />
          </div>
          
          {/* 請假類型選擇 */}
          <div className="backdrop-blur-xl bg-white/20 rounded-3xl border border-white/30 shadow-xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 bg-green-500/80 rounded-lg flex items-center justify-center">
                <FileType className="h-4 w-4 text-white" />
              </div>
              <h3 className="text-lg font-semibold text-white drop-shadow-md">請假類型</h3>
            </div>
            <LeaveTypeSelector 
              form={form}
              selectedLeaveType={selectedLeaveType}
            />
          </div>
          
          {/* 請假詳情 */}
          <div className="backdrop-blur-xl bg-white/20 rounded-3xl border border-white/30 shadow-xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 bg-orange-500/80 rounded-lg flex items-center justify-center">
                <MessageSquare className="h-4 w-4 text-white" />
              </div>
              <h3 className="text-lg font-semibold text-white drop-shadow-md">請假詳情</h3>
            </div>
            <LeaveFormDetails 
              form={form}
              selectedLeaveType={selectedLeaveType}
            />
          </div>
          
          {/* 審核流程 */}
          <div className="backdrop-blur-xl bg-white/20 rounded-3xl border border-white/30 shadow-xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 bg-purple-500/80 rounded-lg flex items-center justify-center">
                <GitBranch className="h-4 w-4 text-white" />
              </div>
              <h3 className="text-lg font-semibold text-white drop-shadow-md">審核流程</h3>
            </div>
            <LeaveApprovalWorkflow approvers={approvers} />
          </div>

          {/* 提交按鈕 */}
          <div className="flex justify-center pt-4">
            <Button 
              type="submit" 
              className={`w-full sm:w-auto px-12 py-3 text-lg font-semibold ${visionProStyles.glassButton} border-white/40 text-white hover:bg-white/30 transition-all duration-300 shadow-2xl flex items-center gap-3`}
            >
              <Send className="h-5 w-5" />
              提交請假申請
            </Button>
          </div>
        </form>
      </Form>
    </div>
  );
}

export default LeaveRequestForm;
